import Foundation

struct LanguageOption: Identifiable, Hashable {
    let code: String
    let name: String

    var id: String { code }
}

enum AppLanguages {
    static let all: [LanguageOption] = [
        .init(code: "af", name: "Afrikaans"),
        .init(code: "ak", name: "Akan (Twi)"),
        .init(code: "sq", name: "Albanian"),
        .init(code: "am", name: "Amharic"),
        .init(code: "ar", name: "Arabic"),
        .init(code: "hy", name: "Armenian"),
        .init(code: "as", name: "Assamese"),
        .init(code: "ay", name: "Aymara"),
        .init(code: "az", name: "Azerbaijani"),
        .init(code: "bm", name: "Bambara"),
        .init(code: "eu", name: "Basque"),
        .init(code: "be", name: "Belarusian"),
        .init(code: "bn", name: "Bengali"),
        .init(code: "bh", name: "Bhojpuri"),
        .init(code: "bs", name: "Bosnian"),
        .init(code: "br", name: "Breton"),
        .init(code: "bg", name: "Bulgarian"),
        .init(code: "my", name: "Myanmar (Burmese)"),
        .init(code: "ca", name: "Catalan"),
        .init(code: "yue", name: "Cantonese"),
        .init(code: "ceb", name: "Cebuano"),
        .init(code: "zh-CN", name: "Chinese (Simplified)"),
        .init(code: "zh-TW", name: "Chinese (Traditional)"),
        .init(code: "co", name: "Corsican"),
        .init(code: "hr", name: "Croatian"),
        .init(code: "cs", name: "Czech"),
        .init(code: "da", name: "Danish"),
        .init(code: "prs", name: "Dari (Afghan Persian)"),
        .init(code: "dv", name: "Dhivehi"),
        .init(code: "nl", name: "Dutch"),
        .init(code: "dz", name: "Dzongkha"),
        .init(code: "en", name: "English"),
        .init(code: "eo", name: "Esperanto"),
        .init(code: "et", name: "Estonian"),
        .init(code: "fil", name: "Filipino (Tagalog)"),
        .init(code: "fi", name: "Finnish"),
        .init(code: "fr", name: "French"),
        .init(code: "fy", name: "Frisian"),
        .init(code: "ff", name: "Fula"),
        .init(code: "gl", name: "Galician"),
        .init(code: "ka", name: "Georgian"),
        .init(code: "de", name: "German"),
        .init(code: "el", name: "Greek"),
        .init(code: "gn", name: "Guarani"),
        .init(code: "gu", name: "Gujarati"),
        .init(code: "ht", name: "Haitian Creole"),
        .init(code: "ha", name: "Hausa"),
        .init(code: "haw", name: "Hawaiian"),
        .init(code: "he", name: "Hebrew"),
        .init(code: "hi", name: "Hindi"),
        .init(code: "hmn", name: "Hmong"),
        .init(code: "hu", name: "Hungarian"),
        .init(code: "is", name: "Icelandic"),
        .init(code: "ig", name: "Igbo"),
        .init(code: "ilo", name: "Iloko"),
        .init(code: "id", name: "Indonesian"),
        .init(code: "ga", name: "Irish"),
        .init(code: "it", name: "Italian"),
        .init(code: "ja", name: "Japanese"),
        .init(code: "jv", name: "Javanese"),
        .init(code: "kn", name: "Kannada"),
        .init(code: "kk", name: "Kazakh"),
        .init(code: "km", name: "Khmer"),
        .init(code: "rw", name: "Kinyarwanda"),
        .init(code: "kri", name: "Krio"),
        .init(code: "ko", name: "Korean"),
        .init(code: "ku", name: "Kurdish (Kurmanji)"),
        .init(code: "ckb", name: "Kurdish (Sorani)"),
        .init(code: "ky", name: "Kyrgyz"),
        .init(code: "lo", name: "Lao"),
        .init(code: "la", name: "Latin"),
        .init(code: "lv", name: "Latvian"),
        .init(code: "ln", name: "Lingala"),
        .init(code: "lt", name: "Lithuanian"),
        .init(code: "lb", name: "Luxembourgish"),
        .init(code: "mk", name: "Macedonian"),
        .init(code: "mai", name: "Maithili"),
        .init(code: "mg", name: "Malagasy"),
        .init(code: "ms", name: "Malay"),
        .init(code: "ml", name: "Malayalam"),
        .init(code: "mt", name: "Maltese"),
        .init(code: "mi", name: "Maori"),
        .init(code: "mr", name: "Marathi"),
        .init(code: "mni-Mtei", name: "Meiteilon (Manipuri)"),
        .init(code: "mn", name: "Mongolian"),
        .init(code: "zgh", name: "Moroccan"),
        .init(code: "ne", name: "Nepali"),
        .init(code: "nso", name: "Northern Sotho (Sepedi)"),
        .init(code: "no", name: "Norwegian"),
        .init(code: "oc", name: "Occitan"),
        .init(code: "or", name: "Odia (Oriya)"),
        .init(code: "om", name: "Oromo"),
        .init(code: "pam", name: "Pampangan (Kapampangan)"),
        .init(code: "pap", name: "Papiamento"),
        .init(code: "ps", name: "Pashto"),
        .init(code: "fa", name: "Persian"),
        .init(code: "pl", name: "Polish"),
        .init(code: "pt", name: "Portuguese"),
        .init(code: "pa", name: "Punjabi"),
        .init(code: "qu", name: "Quechua"),
        .init(code: "ro", name: "Romanian"),
        .init(code: "ru", name: "Russian"),
        .init(code: "sm", name: "Samoan"),
        .init(code: "sa", name: "Sanskrit"),
        .init(code: "gd", name: "Scots Gaelic"),
        .init(code: "sr", name: "Serbian"),
        .init(code: "scn", name: "Sicilian"),
        .init(code: "szl", name: "Silesian"),
        .init(code: "shn", name: "Shan"),
        .init(code: "sn", name: "Shona"),
        .init(code: "sd", name: "Sindhi"),
        .init(code: "si", name: "Sinhala"),
        .init(code: "sk", name: "Slovak"),
        .init(code: "sl", name: "Slovenian"),
        .init(code: "so", name: "Somali"),
        .init(code: "st", name: "Sesotho"),
        .init(code: "ss", name: "Swati"),
        .init(code: "es", name: "Spanish"),
        .init(code: "su", name: "Sundanese"),
        .init(code: "sw", name: "Swahili"),
        .init(code: "sv", name: "Swedish"),
        .init(code: "tl", name: "Tagalog"),
        .init(code: "tg", name: "Tajik"),
        .init(code: "ta", name: "Tamil"),
        .init(code: "tt", name: "Tatar"),
        .init(code: "te", name: "Telugu"),
        .init(code: "tet", name: "Tetum"),
        .init(code: "th", name: "Thai"),
        .init(code: "bo", name: "Tibetan"),
        .init(code: "ti", name: "Tigrinya"),
        .init(code: "tpi", name: "Tok Pisin"),
        .init(code: "to", name: "Tongan"),
        .init(code: "tr", name: "Turkish"),
        .init(code: "tk", name: "Turkmen"),
        .init(code: "ts", name: "Tsonga"),
        .init(code: "tn", name: "Tswana"),
        .init(code: "ug", name: "Uyghur"),
        .init(code: "uk", name: "Ukrainian"),
        .init(code: "ur", name: "Urdu"),
        .init(code: "uz", name: "Uzbek"),
        .init(code: "vi", name: "Vietnamese"),
        .init(code: "cy", name: "Welsh"),
        .init(code: "wo", name: "Wolof"),
        .init(code: "xh", name: "Xhosa"),
        .init(code: "yi", name: "Yiddish"),
        .init(code: "yo", name: "Yoruba"),
        .init(code: "zu", name: "Zulu")
    ]

    static func name(for code: String) -> String {
        all.first(where: { $0.code == code })?.name ?? code
    }
}
